from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MIF_PATH = ROOT / "SparrowRV" / "bsp" / "obj" / "SparrowRV.mif"
OUT_PATH = ROOT / "SparrowRV" / "rtl" / "core" / "gowin_dpb_iram.v"

RAM_DEPTH = 8192
WORD_BYTES = 4
BANK_DEPTH = 2048
INIT_CHUNKS = 64
BYTES_PER_INIT = 32


def read_words(path):
    words = []
    for raw in path.read_text(encoding="ascii").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("//"):
            continue
        words.append(int(line, 16) & 0xFFFFFFFF)
    words.extend([0] * (RAM_DEPTH - len(words)))
    return words[:RAM_DEPTH]


def init_hex(words, bank, byte_lane, chunk):
    start = bank * BANK_DEPTH + chunk * BYTES_PER_INIT
    values = []
    for index in range(BYTES_PER_INIT):
        word = words[start + index]
        values.append((word >> (8 * byte_lane)) & 0xFF)
    return "".join(f"{value:02X}" for value in reversed(values))


def instance_name(bank, byte_lane):
    return f"u_b{bank}_byte{byte_lane}"


def emit_instance(bank, byte_lane):
    name = instance_name(bank, byte_lane)
    out_bit = f"[{byte_lane}]"
    din_slice = f"[{byte_lane * 8 + 7}:{byte_lane * 8}]"
    lines = [
        f"    wire [15:0] doa_b{bank}_byte{byte_lane};",
        f"    wire [15:0] dob_b{bank}_byte{byte_lane};",
        "",
        f"    DPB {name} (",
        f"        .DOA(doa_b{bank}_byte{byte_lane}),",
        f"        .DOB(dob_b{bank}_byte{byte_lane}),",
        "        .CLKA(clk),",
        "        .OCEA(1'b1),",
        "        .CEA(ena),",
        "        .RESETA(1'b0),",
        f"        .WREA(wea & wema{out_bit}),",
        "        .CLKB(clk),",
        "        .OCEB(1'b1),",
        "        .CEB(enb),",
        "        .RESETB(1'b0),",
        f"        .WREB(web & wemb{out_bit}),",
        "        .BLKSELA({1'b0, addra[12:11]}),",
        "        .BLKSELB({1'b0, addrb[12:11]}),",
        "        .ADA({addra[10:0], 3'b000}),",
        f"        .DIA({{8'h00, dina{din_slice}}}),",
        "        .ADB({addrb[10:0], 3'b000}),",
        f"        .DIB({{8'h00, dinb{din_slice}}})",
        "    );",
        f"    defparam {name}.READ_MODE0 = 1'b0;",
        f"    defparam {name}.READ_MODE1 = 1'b0;",
        f"    defparam {name}.WRITE_MODE0 = 2'b00;",
        f"    defparam {name}.WRITE_MODE1 = 2'b00;",
        f"    defparam {name}.BIT_WIDTH_0 = 8;",
        f"    defparam {name}.BIT_WIDTH_1 = 8;",
        f"    defparam {name}.BLK_SEL_0 = 3'b{bank:03b};",
        f"    defparam {name}.BLK_SEL_1 = 3'b{bank:03b};",
        f"    defparam {name}.RESET_MODE = \"SYNC\";",
    ]
    return lines


def emit_module(words):
    lines = [
        "// Generated by labs/lab3_sparrowrv/scripts/generate_gowin_iram.py",
        "// Gowin DPB primitives are used to avoid unsupported inferred read-before-write mode.",
        "module gowin_dpb_iram (",
        "    input wire clk,",
        "    input wire [12:0] addra,",
        "    input wire [12:0] addrb,",
        "    input wire [31:0] dina,",
        "    input wire [31:0] dinb,",
        "    input wire wea,",
        "    input wire web,",
        "    input wire [3:0] wema,",
        "    input wire [3:0] wemb,",
        "    input wire ena,",
        "    input wire enb,",
        "    output wire [31:0] douta,",
        "    output wire [31:0] doutb",
        ");",
        "",
    ]

    for bank in range(4):
        for byte_lane in range(4):
            lines.extend(emit_instance(bank, byte_lane))
            for chunk in range(INIT_CHUNKS):
                lines.append(
                    f"    defparam {instance_name(bank, byte_lane)}.INIT_RAM_{chunk:02X} = "
                    f"256'h{init_hex(words, bank, byte_lane, chunk)};"
                )
            lines.append("")

    for byte_lane in range(4):
        hi = byte_lane * 8 + 7
        lo = byte_lane * 8
        cases_a = []
        cases_b = []
        for bank in range(4):
            cases_a.append(f"(addra[12:11] == 2'd{bank}) ? doa_b{bank}_byte{byte_lane}[7:0]")
            cases_b.append(f"(addrb[12:11] == 2'd{bank}) ? dob_b{bank}_byte{byte_lane}[7:0]")
        lines.append(f"    assign douta[{hi}:{lo}] = " + " : ".join(cases_a) + " : 8'h00;")
        lines.append(f"    assign doutb[{hi}:{lo}] = " + " : ".join(cases_b) + " : 8'h00;")
    lines.extend(["", "endmodule", ""])
    return "\n".join(lines)


def main():
    if not MIF_PATH.exists():
        raise SystemExit(f"Missing MIF: {MIF_PATH}")
    OUT_PATH.write_text(emit_module(read_words(MIF_PATH)), encoding="ascii")
    print(f"Generated {OUT_PATH}")


if __name__ == "__main__":
    main()
